apiVersion: apps/v1
kind: Deployment
metadata:
 name: ${Service}
 namespace: ${NS}
 labels:
  app: ${Service}
  release: ${release}
spec:
 replicas: ${server_replicas}
 selector:
  matchLabels:
   app: ${Service}
   release: ${release}
 template:
  metadata:
   labels:
    app: ${Service}
    release: ${release}
  spec:
   containers:
   - name: ${Service}
     image: ${REPOSITORY}
     args: ["--model_config_file=/models/multimodel/model.config"]
     resources:
      requests:
       memory: "${request_mem}"
      limits:
       memory: "${limit_mem}"
     ports:
     - name: http
       containerPort: ${httpPort}
     - name: tcp
       containerPort: ${tcpPort}
     volumeMounts:
     - mountPath: ${mountPath}
       name: ${Service}
   volumes:
   - name: ${Service}
     persistentVolumeClaim:
       claimName: ${pvcClaim}
   imagePullSecrets:
   - name: registry-secret